# docker-compose.yml
version: '3.8'

services:
  # Windows build environment
  windows-builder:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      powershell -Command "
      # Install build tools
      choco install cmake visualstudio2019buildtools -y;
      # Build project
      cmake -B build -G 'Visual Studio 16 2019';
      cmake --build build --config Release;
      "

  # Android build environment  
  android-builder:
    image: androidsdk/android-ndk:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_NDK_HOME=/opt/android-ndk
    command: >
      bash -c "
      cmake -B build-android 
        -DCMAKE_TOOLCHAIN_FILE=$$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake 
        -DANDROID_ABI=arm64-v8a 
        -DANDROID_NATIVE_API_LEVEL=21 
        -DANDROID_BUILD=ON &&
      cmake --build build-android
      "

  # Development environment
  dev-environment:
    image: ubuntu:20.04
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y build-essential cmake git &&
      cmake -B build -DLINUX_BUILD=ON &&
      cmake --build build
      "
